### ISSUE TITLE
parsing dicts in a list (support a list on top level of a JSON document)

### ISSUE THREAD

**Issue by smjure** [TeskaLabs/cysimdjson#10]
Thanks for the great wrapper, awsome results. I get data which contain dicts in a list, sth like this:

`m = b'[{"evl":"Quest","DAY":"Monday","classes":[1,2,6,9],"sub1":10.23,"sub2":-13.123,"sub3":2.01,"hours1":200,"hours2":4000,"date":1607614205,"signature":1},{"evl":"Quest","DAY":"Monday","classes":[1,2,6,9],"sub1":10.23,"sub2":-13.123,"sub3":2.01,"hours1":200,"hours2":4000,"date":1607614205,"signature":1},{"evl":"Quest","DAY":"Monday","classes":[1,2,6,9],"sub1":10.23,"sub2":-13.123,"sub3":2.01,"hours1":200,"hours2":4000,"date":1607614205,"signature":1},]'`

Have tried it with `cysimdjson.JSONParser()` but no success, is there any possible workaround? Thanks..

**Comment by ateska** [comment]
Thanks for reporting, we will look at that.
