### ISSUE TITLE
Error when installing 21.11b2 from pypi

### ISSUE THREAD

**Issue by amirotin** [TeskaLabs/cysimdjson#27]
Hi.
When i try to install latest version from pypi i get this error: `ValueError: 'cysimdjson/cysimdjson.pyx' doesn't match any files`
Looks like cysimdjson.pyx is missing.

**Comment by aprilahijriyan** [comment]
Experiencing the same thing on mac m1

**Comment by ateska** [comment]
Fixed, will be released to pypi immediately.
