### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by amirotin** [TeskaLabs/cysimdjson#28]
Hi!
There is no **sys.getdlopenflags** on winows, so entire package won't work here. 
https://github.com/TeskaLabs/cysimdjson/blob/3515a3a345f0d4c748a79042928257f25197a3fb/cysimdjson/__init__.py#L7

Better to add check for platform, something like `sys.platform != 'win32'`

**Comment by ateska** [comment]
Ok, good point.
