### ISSUE TITLE
How to convert to a dict when needed?

### ISSUE THREAD

**Issue by pushshift** [TeskaLabs/cysimdjson#37]
What is the best way to convert to a dict? I tried dict(obj) and was able to get a dict but some keys are still things like <cysimdjson.cysimdjson.JSONArray object at 0x7f523a0ff090>

Would creating a method to recursively go through the fields and convert be the best method or is there a built-in method to convert a JSON with nested fields / arrays into a dict? I understand the sacrifice in speed but we would only be doing this with JSON objects that match a specific key value within the JSON. 

Thanks so much for this amazing module! It is amazingly fast.

**Comment by TkTech** [comment]
You're looking for `export()`.

**Comment by pushshift** [comment]
Thank you sir!
